### ISSUE TITLE
[Error] `tl types` has returned an empty response.

### ISSUE THREAD

**Issue by ghsttwn** [teal-language/vscode-teal#42]
Just installed the vscode-teal extension through the editor itself, version 1.57.1, Windows 10.

![image](https://user-images.githubusercontent.com/86124825/123520022-4b21f880-d674-11eb-85e5-53b176b9340d.png)

When run from PowerShell, `tl types` does work perfectly fine.

Edit: I'm running tl 0.13.1. I'll check if this happens in latest master branch.

**Comment by pdesaulniers** [comment]
OK, I've seen this error before: https://github.com/teal-language/vscode-teal/issues/34 

How did you install `tl`? Did you use LuaRocks?

**Comment by pdesaulniers** [comment]
In any case, I assume Node.js is unable to find `tl` in the PATH for some reason. The extension is probably failing to detect the ENOENT correctly...

**Comment by ghsttwn** [comment]
> How did you install tl? Did you use LuaRocks?

Yes, using LuaRocks 3.5.0. I'm managing my Lua install using [hererocks](https://github.com/luarocks/hererocks).

Instead of relying in Node.js magic, what about letting the user choose a path where tl is located? It could first search for it in the PATH and then, if it is not found, use the one at `tl.compilerPath` instead.

**Comment by pdesaulniers** [comment]
> Yes, using LuaRocks 3.5.0. I'm managing my Lua install using hererocks.

OK, good. Can you please run `cmd.exe` and check if `tl` is available in the PATH? If not, can you add it to the PATH and check if that fixes the issue?

> Instead of relying in Node.js magic, what about letting the user choose a path where tl is located?

The extension used to have an option for customizing the compiler path, but it lead to some issues due to how `LUA_PATH` works. Regardless of the `tl.compilerPath` setting, the `tl` driver would `require` the first `tl.lua` that it would find in the `LUA_PATH`. So, it could pick the wrong file in some cases :/

**Comment by ghsttwn** [comment]
> Can you please run cmd.exe and check if tl is available in the PATH?

It worked! But that just defeats the whole purpose of using hererocks to manage different Lua versions for me. 😞
The cool thing about my setup at least is that I can change a `$LuaVersion` variable in PowerShell and get that version up and running easily.

What about bundling `tl.lua` into the project? Something like [fengari](https://fengari.io/) or even [wasmoon](https://github.com/ceifa/wasmoon) would do the job of running it. Relying in the user compiler could lead to inconsistencies and errors because of different versions being tested.

**Comment by pdesaulniers** [comment]
Yes, I think this could be a good solution. I'll think about it!

Instead of running tl.lua using fengari, it would probably be easier to bundle platform-dependent `tl` executables with the extension. The tl releases on GitHub provide standalone executables for Windows and Linux, which could be used for this purpose.

**Comment by pdesaulniers** [comment]
The error message should be indirectly fixed by https://github.com/teal-language/vscode-teal/commit/85cffb7e6452fcd72b35d11fb7485081c7da4d5f.

The extension will now display the following message when opening a file, if `tl` cannot be found:

> Could not find the tl executable. Please make sure that it is available in the PATH.
>
> Type-checking has been disabled for this file.

I'm closing this issue in favor of https://github.com/teal-language/vscode-teal/issues/44. Thanks!

**Comment by ghsttwn** [comment]
> The error message should be indirectly fixed by 85cffb7.

Though the error I reported actually got fixed with ae605c9 somehow, that was the other thing I wanted to open an issue for, because it became an annoyance while breaking stuff in my existing codebase. I'm glad it's fixed!
