### ISSUE TITLE
support multi tlconfig.lua

### ISSUE THREAD

**Issue by virusdefender** [teal-language/vscode-teal#43]
Now the vscode-teal plugin will run `tl` command in the root of the workspace, so tl will use `tlconfig.lua` in this dir, it's ok if the workspace only contains one teal project, you can add the source dir to `tlconfig.lua` like `project_name/src/`.

However, sometimes we need to develop some independent projects in one workspace, so the `include_dir` may conflict if different projects contains the same file name. Demo: https://github.com/virusdefender/tlproject

If you want to edit `project2/main.tl`, you need to change `include_dir` to `project2`, if you want to edit `project1/main.tl`, you need to change `include_dir` to `project1`, or wrong `functions.tl` will be loaded, it's very inconvenient.

It seems `tl` supports searching `tlconfig.lua` outside current dir (https://github.com/teal-language/tl/blob/15bb48baa3a1055e6ae664ccb530665b49c7e02c/tl#L892), if vscode-teal run tl command with `cwd = dirname(file_to_check_or_get_types)`, `tl` will use `tlconfig.lua` in the root of project instead of the root worksapce, so the problem in demo project can be avoided.

**Comment by pdesaulniers** [comment]
Should be fixed by https://github.com/teal-language/vscode-teal/commit/717a482027d1207c3a6839233e72d1867a261825.

The behavior is now the following:

- If `tlconfig.lua`can be found in the parent directories of the source file, the extension will run `tl` with `cwd = <directory of the nearest tlconfig.lua file>`.
- Otherwise, the extension will run `tl` at the root of the workspace.
