### ISSUE TITLE
Teal.plist request

### ISSUE THREAD

**Issue by rosingrind** [teal-language/vscode-teal#56]
I would like to ask if you have any official `.plist` grammar file for use in `.tmbundle`:

- does this/alternative plugin repo provide the `.plist` one?
- if so, would you mind to share it by any license?
- if not, is [teal.tmLanguage.json](https://github.com/teal-language/vscode-teal/blob/master/syntaxes/teal.tmLanguage.json) considered as official and up-to-date grammar source?
- would you mind if I use any grammar file in any open project?

I'm requesting this info because many other IDEs and editors support classic `.tmbundle` format for basic grammar support out of the box. Releasing one will allow others to use Teal with comfort or make custom plugin implementations (as it is easily converted).

In case you don't understand what do I mean behind `.tmbundle` packaging, look up any official repo such as https://github.com/textmate/lua.tmbundle

**Comment by pdesaulniers** [comment]
Hello! :)

> does this/alternative plugin repo provide the .plist one?

This repo does not currently provide a `.plist` file, only the `tmLanguage.json` grammar. I'm not aware of other repos which provide a `.plist`.

I suppose there are some tools which can convert the JSON file into a `.plist`, but I've never used them...

> if not, is [teal.tmLanguage.json](https://github.com/teal-language/vscode-teal/blob/master/syntaxes/teal.tmLanguage.json) considered as official and up-to-date grammar source?

Yes, I wrote the JSON file by hand, it wasn't generated from a `.plist` file.

> would you mind if I use any grammar file in any open project?

No, that would be great! The JSON grammar file is licensed under the MIT license.

> I'm requesting this info because many other IDEs and editors support classic .tmbundle format for basic grammar support out of the box. Releasing one will allow others to use Teal with comfort or make custom plugin implementations (as it is easily converted).

Yes, I agree, I think it would make sense to maintain a `.tmbundle`. Then, I could generate the `tmLanguage.json` grammar from the `.plist` file, instead of writing the JSON file directly.

For testing purposes: beside TextMate, what are some popular text editors which support this format? I think Sublime Text does?

**Comment by rosingrind** [comment]
Thank you for your reply! That's some great news :)

Just in case: with increased portability, TextMate's `.plist` grammars may introduce problems as it's not that modern and mostly used to generate other grammar packs. I tried to write `.bnf` syntaxes, it was epic, don't know too much about TextMate's `.plist` syntax details tho...

> For testing purposes: beside TextMate, what are some popular text editors which support this format? I think Sublime Text does?

TextMate bundles are natively supported in all JetBrains products. Sublime Text and NetBeans, as VS Code, support them by producing own `.tmSnippet`, `.tmLanguage` or `.tmTheme` files from the bundle. Visual Studio may load them in [many forms](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2017/extensibility/adding-an-lsp-extension?view=vs-2017#textmate-grammar-files), some other editors such as [LiClipse](https://www.liclipse.com) or [Textastic for iPad](https://www.textasticapp.com/v9/manual/customization/custom_syntax_themes_templates.html) also support bundles natively. Even GitHub's [Linguist](https://github.com/github/linguist) uses [them](https://github.com/github/linguist/blob/master/vendor/README.md).

I can't really tell how widely `.plist` bundle grammars are used, I just know that `.json` grammars are produced from them, hence they may differ from editor to editor. I think generating `.plsit` from [teal.tmLanguage.json](https://github.com/teal-language/vscode-teal/blob/master/syntaxes/teal.tmLanguage.json) via VSCode [plugin](https://marketplace.visualstudio.com/items?itemName=Togusa09.tmlanguage) should work. I can try to make and transfer you a raw bundle if you'd like to try to switch to different grammar base, but if you're already into this idea, I'll be glad to offer any help or support :)

**Comment by pdesaulniers** [comment]
OK, I made a TextMate bundle: https://github.com/pdesaulniers/teal.tmbundle

I tested it in Intellij IDEA, and it seems to work reasonably well. At least, the keywords are highlighted. The types don't appear to have any syntax highlighting, but it's a start :)

![image](https://user-images.githubusercontent.com/23723605/219822404-2e41a0fe-2efb-4ed8-a06c-13b3298a482f.png)

**Comment by rosingrind** [comment]
Thank you, this is awesome!

No type highlighting is not a big deal for `.tmbundle` case as I usually don't expext them to do complex things - you can always use a separate checking build stage when developing on a language with typing extensions, and I do so. Just keep grammars updated if something breaking changes in Teal/Lua, and I think it'll be all right.

Actually, the best part of this is Teal now have official reference to do any complex plugin for any editor. Better yet, you can try and promote it to Linguist team and even get support over Github's code spaces :)

Again, thank you so much @pdesaulniers, the issue may be closed.

**Comment by pdesaulniers** [comment]
Awesome! Feel free to open an issue in https://github.com/teal-language/teal.tmbundle if there are some issues with the bundle.

> No type highlighting is not a big deal for .tmbundle case as I usually don't expext them to do complex things

I think it occurs because the language rules in the grammar don't always follow TextMate's naming conventions, so IDEA doesn't know how to highlight the tokens: https://macromates.com/manual/en/language_grammars#naming_conventions

If I assign some more generic names to the tokens, it should improve the syntax highlighting in most text editors.

For reference, here's what it looks like in VSCode:

![image](https://user-images.githubusercontent.com/23723605/219865063-20a282d4-16a2-4d56-b77e-231baf169063.png)
