### ISSUE TITLE
Could not find teal in the $PATH

### ISSUE THREAD

**Issue by gloirekiba** [teal-language/vscode-teal#57]
As you can see in the screenshot, teal is currently installed and available in the $PATH but vscode-teal can not find it,  if find it only when installed globaly
![Screenshot from 2023-05-17 04-14-15](https://github.com/teal-language/vscode-teal/assets/94308564/e4237609-f0f8-4f67-b3fd-6f27de5040ba)

**Comment by pdesaulniers** [comment]
Hello,

On my machine, `tl` is located at `~/.local/bin/tl`, and the extension is able to find it.

For the time being, I don't really know why this is happening. Here are a couple questions in order to debug this:

- How did you add `tl` to the `$PATH`?
- What is the default shell on your machine? Is it bash?
- How do you launch vscode?

I suspect that vscode may be using a different `$PATH` than the one in the terminal emulator. This page has some interesting info about how it resolves the shell environment: https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails

(Or perhaps the extension *can* find `tl`, but it fails for a different reason, and the error message is just misleading :))

**Comment by pdesaulniers** [comment]
Hello! I'm going to close the issue for now. Feel free to reopen this issue if you're interested in debugging this.

In any case, I suspect it is a configuration problem. Here are some useful resources if ever you want to investigate this issue further:

- https://github.com/teal-language/tl/issues/660#issuecomment-1552243261
- https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails
