### ISSUE TITLE
I'm getting strange windows MessageBox popups on errors

### ISSUE THREAD

**Issue by morew4rd** [teal-language/vscode-teal#58]
<img width="324" alt="image" src="https://github.com/teal-language/vscode-teal/assets/103900905/8e6a3f4f-5da0-46ff-b8d3-9c4fca4e9a5c">

- It only shows up when there are particular errors (I couldn't classify these, but type issues, syntax errors etc caused these pop-ups often)
- Almost impossible to get rid of, each key hit or mouse click creates a new msgbox. And they block typing because they take the key/mouse focus.
- If I know exactly what the issue is and can correct it from another editor (say notepad) I can work around it. Even then, msgboxs continue popping up until I fix it (but unlike VScode doesn't block the input, so I can type.)
- Otherwise, I just have to disable the plugin.

Not sure if anyone else hit this, is there a workaround?

Also devs: would it be possible to remove messagebox as an error? It doesn't help anything IMO.

**Comment by pdesaulniers** [comment]
Hello! The popup is showing a compiler error. According to this issue, it should have been fixed in tl v0.14.0: https://github.com/teal-language/tl/issues/526

Are you using the most recent version of the Teal compiler (v0.15.2)? If not, can you please try to update the compiler and check if you can still reproduce the issue?

> Also devs: would it be possible to remove messagebox as an error? It doesn't help anything IMO.

I could be wrong, but I believe this messagebox might be generated by the compiler itself and not vscode-teal (at least, I have never seen a similar window on Linux :))

Does the same window show up if you run `tl check <your file.tl>` on the command line?

**Comment by morew4rd** [comment]
Hi and thank you for the information.  Yes, that looks like to be the same as my issue. Strange that it's (was) in the compiler. I very likely have a version prior to 0.14 installed.

I'll close this one, And will report back/reopen it if I see the issue after upgrading and identify the cause with the extension.

Thanks!
